check local dir for mail now

diff --git a/.local/bin/check_mail b/.local/bin/check_mail
--- a/.local/bin/check_mail
+++ b/.local/bin/check_mail
@@ -4,13 +4,14 @@ export DBUS_SESSION_BUS_ADDRESS=`cat $environs 2>/dev/null | tr '\0' '\n' | grep
 export DISPLAY=:0
 export XDG_RUNTIME_DIR="/run/user/1000"
 
-count=$(timeout 6 ssh -i /home/jer/.ssh/id_rsa jer@jer.cx 'ls ~/.mail/new' | wc -l)
+count="$(ls $(find "$HOME/.mail" -name Inbox)/new | wc -l)"
 
 if [ "$?" -ne 0 ]; then
-	echo 'SSH failed or surpassed timeout' >&2 
+	echo 'SSH failed or surpassed timeout' 1>&2 
 	exit 1
 fi
 
+echo $count
 if [ "$count" -gt 0 ]; then
 	play "$HOME/Media/Audio/Recordings/bow.mp3" vol 0.25 & 
 	notify-send 'Mail' "You've got $count new mail."
