minor fixes

diff --git a/.local/bin/vimctl b/.local/bin/vimctl
--- a/.local/bin/vimctl
+++ b/.local/bin/vimctl
@@ -9,20 +9,24 @@ excmd() {
 }
 
 die() {
-	echo "$*" 1>&2
+	echo "$0: $*" 1>&2
 	exit 1
 }
 
-while getopts ":e:" opt; do 
+if [ "$#" -eq 0 ]; then
+	die "provide arguments"
+fi
+
+if getopts ":e" opt; then 
+	shift $((OPTIND - 1))
 	case "${opt}" in
-		e) excmd "$OPTARG"
+		e) excmd "$*"
 			;;
-		\?) die "Invalid option: $OPTARG"
+		\?) die "invalid option - '$OPTARG'"
 			;;
-		:) die "Invalid option: $OPTARG requires an argument"
+		:) die "invalid option. '$OPTARG' requires an argument"
 			;;
 	esac
-done
-shift $((OPTIND - 1))
-
-[ $# -gt 0 ] && send "$*"
+else
+	send "$*"
+fi
